backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "actions"
    label: "Actions"
    folder: "content/actions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    path: "{{slug}}/index.md"
    media_folder: "images"
    public_folder: "images"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Résumé", name: "excerpt", widget: "text", required: false}
      - label: "Image principale"
        name: "featured_image"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Description / Alt", name: "alt", widget: "string", required: false}
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Description / Alt", name: "alt", widget: "string", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "news"
    label: "Actualités"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    path: "{{slug}}/index.md"
    media_folder: "images"
    public_folder: "images"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Résumé", name: "excerpt", widget: "text", required: false}
      - label: "Image principale"
        name: "featured_image"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Description / Alt", name: "alt", widget: "string", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "press"
    label: "Presse"
    folder: "content/press"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    path: "{{slug}}/index.md"
    media_folder: "images"
    public_folder: "images"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Résumé", name: "excerpt", widget: "text", required: false}
      - label: "Source"
        name: "source"
        widget: "object"
        required: false
        fields:
          - {label: "Nom", name: "name", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - {label: "Lien", name: "link", widget: "string", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
