backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow # Use editorial workflow for 

# Possibly useful settings
# site_url: "https://acppt.org" # URL of the site
# show_preview_links: true # Show preview links in the admin interface
# slug:
#   encoding: "ascii" # Use unicode slugs
#   clean_accents: true # Clean accents in slugs
#   sanitize_replacement: "-" # Replace spaces with dashes
# editor:
#   preview: true # Show preview in the editor
logo_url: "/images/logo.png" # URL of the logo in the admin interface

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

locale: "fr" # Set the locale for the admin interface

collections:
  - name: "actions"
    label: "Actions"
    label_singular: "Action"
    folder: "content/actions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    path: "{{slug}}/index.md"
    media_folder: "images"
    public_folder: "images"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Résumé", name: "excerpt", widget: "text", required: false}
      - label: "Image principale"
        name: "featured_image"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Description / Alt", name: "alt", widget: "string", required: false}
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Description / Alt", name: "alt", widget: "string", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "news"
    label: "Actualités"
    label_singular: "Actualité"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    path: "{{slug}}/index.md"
    media_folder: "images"
    public_folder: "images"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Résumé", name: "excerpt", widget: "text", required: false}
      - label: "Image principale"
        name: "featured_image"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Description / Alt", name: "alt", widget: "string", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "press"
    label: "Articles de presse"
    label_singular: "Article de presse"
    folder: "content/press"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    path: "{{slug}}/index.md"
    media_folder: "images"
    public_folder: "images"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Résumé", name: "excerpt", widget: "text", required: false}
      - label: "Source"
        name: "source"
        widget: "object"
        required: false
        fields:
          - {label: "Nom", name: "name", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - {label: "Lien", name: "link", widget: "string", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
